//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalsApi
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string HospitalLongitude { get; set; }
        public string HospitalLatitude { get; set; }
        public Nullable<int> NumOfAllBed { get; set; }
        public Nullable<int> NumAvailable { get; set; }
    }
}
