//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ID { get; set; }
        public string ReservationDate { get; set; }
        public int PatientID { get; set; }
        public int HospitalID { get; set; }
        public int SpecialtyID { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<bool> AdmitOrDecline { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual OutpatientClinic OutpatientClinic { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
