//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> HospitalID { get; set; }
        public Nullable<int> PatientID { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual RoleUser RoleUser { get; set; }
    }
}
